version: 2.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build_script:
- ps: dotnet pack src\NLog.Targets.Redis --configuration Release --include-symbols
test_script:
- ps: dotnet test .\src\NLog.Targets.Redis.Tests\

nuget:
  disable_publish_on_pr: true

skip_tags: true

artifacts:
  - path: 'src\**\*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: 4vmD+QQvYanyzel1LEipjBuD8a3vyZSV8Gravb4DUI8/FgQj6Cn6vRayUC6Af3AM
  artifact: /.*\.nupkg/
  on:
    branch: master
