version: 0.0.{build}-ci
image: Visual Studio 2017
configuration: Release
platform: Any CPU
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  package_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  # AssemblyVersion should not be touch by the patcher.
  # Per https://github.com/NLog/NLog/issues/1765#issuecomment-261776513
init:
- pwsh: >-
    $tagRelease = $env:appveyor_repo_tag -eq 'true'

    if ($tagRelease) {
        $tag = $env:appveyor_repo_tag_name
        Update-AppveyorBuild -Version "$tag"
    }
build_script:
- ps: dotnet pack src\NLog.Targets.Redis --configuration Release --include-symbols
test_script:
- ps: dotnet test .\src\NLog.Targets.Redis.Tests\

nuget:
  disable_publish_on_pr: true

artifacts:
  - path: 'src\**\*.nupkg'

# deploy:
# - provider: NuGet
#   api_key:
#     secure: DtVDH1ZfIR8E2oDLeSPxfn0WFXw3MCv4WhLkkQQl9LfEHswb5sdxdCYodNKhrKik
#   artifact: /.*\.nupkg/
#   on:
#     APPVEYOR_REPO_TAG: true
